__title__ = 'swiftype_enterprise'
__description__ = 'An API client for Swiftype Enterprise'
__url__ = 'https://github.com/swiftype/swiftype-enterprise-python'
__version__ = '1.0.0'
__author__ = 'Swiftype'
__author_email__ = 'eng@swiftype.com'
