__title__ = 'swiftype_enterprise'
__description__ = 'A Deprecated API client for Swiftype Enterprise Search. Use elastic_enterprise_search instead.'
__url__ = 'https://github.com/swiftype/swiftype-enterprise-python'
__version__ = '1.0.1'
__author__ = 'Swiftype'
__author_email__ = 'eng@swiftype.com'
