__title__ = 'elastic_workplace_search'
__description__ = 'An API client for Elastic Workplace Search'
__url__ = 'https://github.com/elastic/workplace-search-python'
__version__ = '0.3.0'
__author__ = 'Elastic'
__author_email__ = 'support@elastic.co'
