name: CI
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Lint
        run: |
          python3.7 -m pip install nox
          nox -s lint

  test:
    env:
      ENDPOINT: http://localhost:8080/api/ws/v1
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    runs-on: ubuntu-latest
    steps:
      # Checkout and Setup Python
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - if: matrix.python-version != '3.7'
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      # Setup Enterprise Search
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Run Enterprise Search
        uses: elastic/elastic-github-actions/enterprise-search@master
        with:
          stack-version: 7.7.0

      # Run tests
      - name: Test
        run: |
          python3.7 -m pip install nox
          nox -s test-${{ matrix.python-version }}
